IGAE/IGAE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('sgrw/', include('IGAEapp.urls')),
    path('admin/', admin.site.urls),
]

IGAE/IGAEapp/urls.py
from django.urls import path
import subprocess
from .controllers import login_ctrl, user_ctrl, scenario_ctrl, app_ctrl

app_name = 'SGRW'
urlpatterns = [
    path('', login_ctrl.index, name='index'),
    path('<str:user_name>/', user_ctrl.user_home, name='user_home'),
    path('<str:user_name>/<str:app_name>/', app_ctrl.app_home, name='app_home'),
    #path('scenario_form', scenario_ctrl.scenario_form, name='scenario_form'),
    path('user_login', login_ctrl.user_login, name='user_login'),
    path('user_logout', login_ctrl.user_logout, name='user_logout'),
    path('<str:user_name>/<str:app_name>/add_scenario', scenario_ctrl.scenario_add, name='add_scenario'),
    path('<str:app_name>/<str:scenario_name>/remove_scenario', scenario_ctrl.remove_scenario, name='remove_scenario'),
    path('<str:user_name>/<str:app>/scenario_create_lr', scenario_ctrl.scenario_create_lr, name='scenario_create_lr'),
    path('<str:user_name>/<str:app>/scenario_create_jmeter', scenario_ctrl.scenario_create_jmeter, name='scenario_create_jmeter'),
    # path('api/<str:app_name>/<str:scenario_name>', scenario_ctrl.scenario_complete_info_json, name='scenario_info_json'),
    # path('api/<str:app_name>/scenario/all', scenario_ctrl.all_scenarios_app_json_info, name='all_scenarios_app_info_json'),
    path('api/scenario/search',scenario_ctrl.scenario_search, name='scenario_search'),
    path('api/robot_scenario/show',scenario_ctrl.retrieve_robot_scenario, name='retrieve_robot_scenario'),
    path('<str:user_name>/new_app_handler', scenario_ctrl.new_app_handler, name='new_app_handler'),
    path('add_user/<str:app_name>', app_ctrl.add_user_to_app, name='add_user_to_app'),
]

IGAE/IGAEapp/models/App.py
from djongo import models
from django.contrib.auth.models import User

class App(models.Model):
    users = models.ManyToManyField(User)
    Name = models.CharField(max_length=50)

    def __str__(self):
        return self.Name
    

IGAE/IGAEapp/models/Clients.py
from djongo import models
from django.contrib.auth.models import User

# class Client(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     Name = models.CharField(max_length=50)

#     def __str__(self):
#         return self.Name

IGAE/IGAEapp/models/Scenario.py
from djongo import models
from .App import App

class Scenario(models.Model):
    app = models.ForeignKey(App, on_delete=models.CASCADE)
    Name = models.CharField(max_length=50)

    def __str__(self):
        return self.Name

IGAE/IGAEapp/models/Transaction.py
from djongo import models
from .Scenario import Scenario

class Transaction(models.Model):
    scenario = models.ForeignKey(Scenario, on_delete=models.CASCADE)
    Name = models.CharField(max_length=100)
    Timestamp = models.BigIntegerField(default=0)
    Avg_time = models.FloatField(default=0)
    Txs_count = models.IntegerField(default=0)
    Type = models.CharField(max_length=100)
    # VuserGroup = models.CharField(max_length=100)
    # Type = models.IntegerField(default=0)
    # StartTime = models.FloatField(default=0.0)
    # EndTime = models.FloatField(default=0.0)
    # AverageTime = models.FloatField(default=0.0)
    # ThinkTime = models.FloatField(default=0.0)
    # WastedTime = models.FloatField(default=0.0)
    # Status = models.IntegerField(default=0)
    # InstanceHandle = models.BigIntegerField(default=0)
    # ParentHandle = models.BigIntegerField(default=0)
    # VuserID = models.IntegerField(default=0)

    def __str__(self):
        return self.Name

IGAE/IGAEapp/models/VuserInfo.py
from djongo import models
from .Scenario import Scenario

class VuserInfo(models.Model):
    scenario = models.ForeignKey(Scenario, on_delete=models.CASCADE)
    Name = models.CharField(max_length=100, default="default")
    Timestamp = models.BigIntegerField(default=0)
    Num_users = models.IntegerField(default=0)
    Type = models.CharField(max_length=100, default="default")
    
    def __str__(self):
        return self.Count

IGAE/IGAEapp/controllers/app_ctrl.py
import json
from ..models import Transaction, App, Scenario
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, Http404, HttpResponseForbidden
from django.template import loader
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db.models import Count
from django.shortcuts import get_object_or_404, render, redirect
from ..models.App import App

def app_home(request, user_name, app_name):
    if request.user.username == user_name:
        user = User.objects.get(username=user_name)
        #user = get_object_or_404(User, pk=user_id)
        try:
            i = 0
            scenarios = list()
            app = user.app_set.get(Name=app_name)

            for apps in user.app_set.all():
                i += 1
            context = {
                'app': app,
            }
            for scenario in app.scenario_set.all():
                scen = {} 
                txs = scenario.transaction_set.values('Name').annotate(Count('Name'))   
                scen["Name"] = scenario.Name
                scen["txs"] = txs
                scenarios.append(scen)   
            context["scenarios"] = scenarios
            context["numApps"] = i
            
            try:
                msg = request.session['msg']
            except KeyError:
                msg = None
            if msg is not None:
                context['msg'] = request.session['msg']
                context["type"] = request.session["type"]
                del request.session['msg']
                del request.session["type"]

            template = loader.get_template('IGAEapp/app_home.html')
            response = HttpResponse(template.render(context, request)) 
            manage_apps(request, app_name, user_name)
            return response
        except App.DoesNotExist:
            return HttpResponseForbidden("App not assigned to this user")

    else:
        return HttpResponseForbidden("User access not granted")

def add_user_to_app(request, app_name):
    if request.user.is_staff and request.POST['username'] != "":
        try:
            user_name = request.POST['username']
            user = User.objects.get(username=user_name)
            app = App.objects.get(Name=app_name)
            app.users.add(user)
            #Necesario avisar en cliente que ha ocurrido (websockets) (routing, consumers, websocket_client)
            return redirect('/sgrw/' + str(request.user.username) + "/" + app_name)
        except User.DoesNotExist:
            return redirect('/sgrw/' + str(request.user.username) + "/" + app_name)
    else:
        return  HttpResponseForbidden("your user cannot do this")

def manage_apps(request, app_name, user_name):
    last_apps = request.session["last-apps"]
    # print("apps", last_apps)
    if user_name in last_apps:

        last_apps_user = last_apps[user_name]
        # last_apps = request.COOKIES['last-apps']
        new_list = list()
        for i in range(0,2):
            try:
                app = last_apps_user[i]
            except: 
                break
            # print(app)
            if app == app_name:
                new_list.insert(0, app)
            else:
                new_list.append(app)
        if len(new_list) == 0 or new_list[0] != app_name:
            new_list.insert(0, app_name)

        # print("last", last_apps_user) #debug
        # print("new list", new_list)
        last_apps[user_name] = new_list
        request.session['last-apps'] = last_apps
    else:
        # print("no last-apps for this user") #debug
        user_profile = list()
        user_profile.append(app_name)
        last_apps[user_name] = user_profile
        request.session["last-apps"] = last_apps

IGAE/IGAEapp/controllers/login_ctrl.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse, Http404, HttpResponseForbidden

from functools import wraps

# class persist_session_vars(object):
#     """ Some views, such as login and logout, will reset all session state.
#     However, we occasionally want to persist some of those session variables.
#     """

#     session_backup = {}

#     def __init__(self, vars):
#         self.vars = vars

#     def __enter__(self):
#         for var in self.vars:
#             self.session_backup[var] = self.request.session.get(var)

#     def __exit__(self, exc_type, exc_value, traceback):
#         for var in self.vars:
#             self.request.session[var] = self.session_backup.get(var)

#     def __call__(self, test_func, *args, **kwargs):

#         @wraps(test_func)
#         def inner(*args, **kwargs):
#             if not args:
#                 raise Exception('Must decorate a view, ie a function taking request as the first parameter')
#             self.request = args[0]
#             with self:
#                 return test_func(*args, **kwargs)

#         return inner

def index(request):
    #comprobar que no exista una sesión ya, en caso contrario, redireccionar a user_home
    if request.user.is_authenticated: 
        return redirect('/sgrw/' + str(request.user.username))
    else :
        template = loader.get_template('IGAEapp/index.html')
        context = {}
        try:
            msg = request.session['msg']
        except KeyError:
            msg = None
        if msg is not None:
            context = {'msg': request.session['msg'], 'type': request.session['type']}
            del request.session['msg']
            del request.session['type']

        return HttpResponse(template.render(context, request))

# @persist_session_vars(['last-apps'])
def user_login(request):
    #user = User.objects.get(Name=request.POST['username'])
    user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
    if user is not None:
        last_apps = None
        try:
            last_apps = request.session["last-apps"]
        except:
            pass
        login(request, user)
        if last_apps == None:
            last_apps = {}
        request.session["last-apps"] = last_apps
        print("login", request.session["last-apps"])
        return redirect('/sgrw/' + str(user.username))
    else:
        request.session['msg'] = "User or Password isn't correct"
        request.session['type'] = "danger"
        return redirect('/sgrw/')
        
# @persist_session_vars(['last-apps'])
def user_logout(request):
    last_apps = request.session["last-apps"]
    logout(request)
    request.session["last-apps"] = last_apps
    request.session['msg'] = "User loged out succesfully"
    request.session['type'] = "success"
    return redirect('/sgrw/')
    #return HttpResponse("Soy " + request.POST['username'] + " y mi contraseña es " + request.POST['password'])


IGAE/IGAEapp/controllers/user_ctrl.py
from django.contrib.auth.models import User
from django.template import loader
from django.http import HttpResponse, Http404, HttpResponseForbidden

def user_home(request, user_name):
    if request.user.username == user_name:
        try: 
            user = User.objects.get(username=user_name)
        except:
            return HttpResponseForbidden("User doesn't exist")
        #user = get_object_or_404(User, pk=user_id)
        if request.user.is_authenticated:
            template = loader.get_template('IGAEapp/user_home.html')
            try:
                last_apps = request.session['last-apps'][user_name]
            except:
                request.session['last-apps'][user_name] = []
                last_apps = []
            print("user_home", last_apps)
            context = {
                'user': user,
                'last_apps': last_apps,
            }
            return HttpResponse(template.render(context, request))
        else:
            return HttpResponseForbidden("User not loged in")
    else:
        print(request.user)
        return HttpResponseForbidden("User access not granted")

IGAE/IGAEapp/templates/IGAEapp/create_scenario.html
<!doctype html>
<html lang="en" style="background-color: white;">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
        <link rel="stylesheet" href="{% static "bootstrap.min.css" %}" />
        <link rel="stylesheet" href="{% static "input.css" %}">
        <link rel="stylesheet" href="{% static "create_scenario.css" %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="{% static "loading.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "loading-btn.css" %}">
        <title>SGRW - creando escenario</title>
    </head>
    <body style="background-color: white;">
        {% if msg %}
                {% if type == 'danger' %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert" style="position: absolute; top: 20px; right: 15px; width: 30%; margin-left: auto; margin-right: 20px; margin-bottom: -10px;">
                {% else %}
                <div class="alert alert-success alert-dismissible fade show" role="alert" style="position: absolute; top: 20px; right: 15px; width: 30%; margin-left: auto; margin-right: 20px; margin-bottom: -10px;">  
                {% endif %}    
                    {{ msg }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        <div style="margin-top: 45px; margin-left: 30%; margin-right: 30%; display: flex;">
            
            <a class="btn btn-outline-secondary rounded-circle" href="javascript: history.go(-1)" style="margin-top: auto; margin-bottom: auto;">
                <em class="fa fa-chevron-left"></em>
            </a>
            <h5 style="margin-left: 15px; color: #0070ad;" class="display-4" >{{ app }} - Añadir escenario</h5>
     
        </div>
        <div style="margin-left: 30%; margin-right: 30%; background-color: white; height: 100%; margin-top: 15px;">
            <ul class="nav nav-tabs" id="myTab" role="tablist" style="display: flex;">
                <li class="nav-item">
                    <a class="nav-link active" id="jmeter-tab" data-toggle="tab" href="#jmeter" role="tab" aria-controls="jmeter" aria-selected="true">Jmeter</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="load-runner-tab" data-toggle="tab" href="#load-runner" role="tab" aria-controls="load-runner" aria-selected="false">Load Runner</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent" style="display: block; margin-left: 50px;">
                <div class="tab-pane fade show active" id="jmeter" role="tabpanel" aria-labelledby="jmeter-tab">
                    <div id="jmeter" style="margin-top: 15px;">
                        <form method="POST" action="{% url 'SGRW:scenario_create_jmeter' user.username app %}" enctype="multipart/form-data" onsubmit="showLoaderJmeter()">
                            {% csrf_token %}
                            <div class="alert alert-info" role="alert" style="margin-top: 25px; border-left: solid 3px #0070ad; border-right: solid 3px #0070ad;">
                                <strong>Nota: </strong>La operación de carga puede tardar de 10~60 segs dependiendo del tamaño del archivo.
                            </div>
                            <div class="form-group">
                                <label for="nameInputJmeter">Nombre escenario</label>
                                <input type="text" class="form-control" id="nameInputJmeter" aria-describedby="nameHelp" placeholder="Introduce nombre" name="escenarioNameJmeter" required>
                                <small id="nameHelp" class="form-text text-muted">Asegurate que identifica inequivocamente al escenario.</small>
                            </div>
                            <label for="input-group mb-3">summary-results.jtl</label>
                            <div class="input-group mb-3" style="width: 100%;">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroupFileJmeter">Subir</span>
                                </div>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="inputGroupFileJmeter01" name="inputGroupFileJmeter01" aria-describedby="inputGroupFileJmeter" required>
                                    <label class="custom-file-label" for="inputGroupFileJmeter01">Elige fichero</label>
                                </div>
                            </div>
                            <div class="dropdown-divider" style="width: 100%; margin-top: 20px; margin-bottom: 15px;"></div>
                            <div>
                                <button type="submit" class="btn btn-primary ld-ext-right" id="submit-btn-jmeter"><div class="ld ld-ring ld-spin"></div>Guardar</button>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="tab-pane fade" id="load-runner" role="tabpanel" aria-labelledby="load-runner-tab">
                    <div id="load-runner" style="margin-top: 10px;">
                        <form method="POST" action="{% url 'SGRW:scenario_create_lr' user.username app %}" enctype="multipart/form-data" onsubmit="showLoaderLR()">
                            {% csrf_token %}
                            <div class="alert alert-warning" role="alert" style="margin-top: 25px; border-left: solid 3px #856404; border-right: solid 3px #856404;">
                                <strong>Atencion: </strong>Asegurate que el fichero está en buenas condiciones. (A veces LR lo exporta mal).
                            </div>
                            <!-- <div class="dropdown-divider" style="width: 100%; margin-bottom: -10px;"></div> -->
                            <div class="form-group">
                                <label for="nameInputLR">Nombre escenario</label>
                                <input type="text" class="form-control" id="nameInputLR" aria-describedby="nameHelp" placeholder="Introduce nombre" name="escenarioNameLR" required>
                                <small id="nameHelp" class="form-text text-muted">Asegurate que identifica inequivocamente al escenario.</small>
                            </div>
                            <label for="input-group mb-3">Json transacciones</label>
                            <div class="input-group mb-3" style="width: 100%;">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="inputGroupFileAddon01">Subir</span>
                                </div>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="inputGroupFile01" name="inputGroupFile01" aria-describedby="inputGroupFileAddon01" required>
                                    <label class="custom-file-label" for="inputGroupFile01">Elige archivo</label>
                                </div>
                            </div>

                            <label for="input-group mb-3">Json usuarios virtuales</label>
                            <div class="input-group mb-3" style="width: 100%;">
                                <div class="input-group-prepend">
                                        <span class="input-group-text" id="inputGroupFileAddon02">Subir</span>
                                    </div>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="inputGroupFile02" name="inputGroupFile02" aria-describedby="inputGroupFileAddon02" required>
                                    <label class="custom-file-label" for="inputGroupFile02">Elige archivo</label>
                                </div>
                            </div>
                            <div class="dropdown-divider" style="width: 100%; margin-top: 20px; margin-bottom: 15px;"></div>
                            <div>
                                <button type="submit" class="btn btn-primary ld-ext-right" id="submit-btn"><div class="ld ld-ring ld-spin"></div>Guardar</button>
                            </div>
                            
                        </form>
                        
                    </div>
                </div>
                
            </div>
        </div>
        <script>
            function showLoaderLR(){
                let button = document.getElementById("submit-btn");
                button.disabled = true;
                button.classList.add("running");
                button.submit();
            }

            function showLoaderJmeter(){
                let button = document.getElementById("submit-btn-jmeter");
                button.disabled = true;
                button.classList.add("running");
                button.submit();
            }
        </script>
        <script src="{% static "jquery-3.3.1.slim.min.js" %}"></script>
        <script src="{% static "popper.min.js" %}"></script>
        <script src="{% static "bootstrap.min.js" %}"></script>  
        <script src="{% static "file_input.js" %}"></script>
    </body>
</html>

IGAE/IGAEapp/templates/IGAEapp/user_home.html
<!doctype html>
<html lang="en" >
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
        <link rel="stylesheet" href="{% static "bootstrap.min.css" %}" />
        <link rel="stylesheet" href="{% static "loader.css" %}">
        <link rel="stylesheet" href="{% static "user_home.css" %}">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        <script src="{% static "lastapps.js" %}"></script>
        <script src="{% static "websocket_bridge.js" %}" type="text/javascript"></script>
        <!--<script src="{% static '/channels/js/websocketbridge.js' %}" type="text/javascript"></script>-->
        <title>{{ user.username }} Home</title>
    </head>
    <style>
        #pane-container {
            margin-left: 9%; margin-right: 9%; background-color: white; border-radius: 5px; margin-top: 40px; height: 100%;
            background-color: rgba(255, 255, 255, 0);
        }

        body {
            background-color: rgba(255, 255, 255, 0);
        }

        html {
            height: 100%;
            background-color: white;
            background-image: url("{% static 'images/sogeti-ilustration.png' %}");
            background-repeat: no-repeat;
            background-size: 350px 440px;
            background-position: right bottom;
        }
    </style>
    <body>
        <!-- Se puede utilizar para mantener el nombre en el login -->
        <div id="pane-container">
            <!-- <nav class="navbar navbar-expand-lg navbar-light" style="border-radius: 10px;">
                <a class="navbar-brand" href="#">
                    <img src="{% static "images/favicon.ico" %}" width="35" height="35" class="d-inline-block align-top">
                    Sogeti
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown" style="margin-left: auto; margin-right: 10px;">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="/sgrw/user_logout">Logout</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav> -->
            <ul class="nav" style="display: flex; margin-left: 30px;">
                <li class="nav-item">
                    <a href="#"><img src="{% static 'images/descarga.png' %}" alt="Sogeti" style="height: 100px; margin-top: -10px; margin-left: 20px;"></a>
                </li>
                <li class="nav-item" style="margin-left: auto; margin-right: 10px; margin-top: 42px;">
                    <div style="display: flex; align-content: flex-end;">
                        <img src="{% static 'images/userIcon.png' %}" alt="{{ user.username }}" style="width: 55px; height: 55px; margin-right: -20px;">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size: 20px; color: #0070ad; margin-top: 10px;">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="/sgrw/user_logout">Logout</a>
                        </div>
                    </div>
                </li>
            </ul>
            <div class="dropdown-divider" style="width: 100%; margin-top: 8px;"></div>
            <div style="margin-top: 170px; margin-bottom: 15px; margin-left: auto; margin-right: auto; width: 30%;">
                <!--<button type="button" class="btn btn-outline-info" data-toggle="modal" data-target="#scenario_form">+ Scenario</button>-->
               
                <!-- <div class="dropdown-divider" style="width: 40%; margin-top: 20px;"></div> -->
                <!-- <p class="lead" style="margin-bottom: 20px;" >Apps:</p> -->
                <form style="display: flex; margin-bottom: 15px; width: 100%;" method="POST" action="{% url 'SGRW:new_app_handler' user.username %}">
                    {% csrf_token %}
                    <!-- <label for="new-app">App: </label> -->
                    <input type="text" id="new-app" placeholder="Enter new app" name="new-app">
                    <button type="submit" class="btn btn-primary" id="submit-btn" > Add </button>
                </form>
                {% if user.app_set.all %}
                    <!-- <div class="list-group" style="margin-top: -10px; margin-right: 15px;">
                        {% for app in user.app_set.all %}
                        <a href="{% url 'SGRW:app_home' user.username app.Name %}" class="list-group-item list-group-item-action">{{ app.Name }}<div class="loader"></div></a>
                        
                        {% endfor %}
                    </div> -->
                <p style="text-align: center; color: #0070ad;">Last apps</p>
                <div id="last-apps">
                {% if last_apps %}
                    {% for app in last_apps %}
                    <a class='app' href="{% url 'SGRW:app_home' user.username app %}"><p style="margin-top: 15px;">{{app}}</p><img src="{% static 'images/favicon.ico' %}" alt="Sogeti" style="width: 40px; height: 40px; margin-top: -15px;"></img></a>
                    {% endfor %}
                {% endif %}
                </div>
                <div id="accordion">
                    <div class="card">
                        <div class="card-header" id="HeadingOne" style="display: flex;">
                            <h5 class="mb-0" style="margin-left: auto; margin-right: auto;">
                                <button class="btn btn-light" data-toggle="collapse" data-target="#appsCollapse" aria-expanded="false" aria-controls="appsCollapse">
                                   All apps
                                </button>
                            </h5>
                        </div>

                        <div id="appsCollapse" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
                            <div class="card-body">
                                <div class="list-group" style="margin-top: -10px; margin-right: 15px;">
                                    {% for app in user.app_set.all %}
                                    <a href="{% url 'SGRW:app_home' user.username app.Name %}" class="list-group-item list-group-item-action" style="width: 100%;">{{ app.Name }}<div class="loader"></div></a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
                    

                {% else %}
                <div class="alert alert-warning" role="alert" style="position: absolute; top: 20px; right: 15px; width: 30%; margin-left: auto; margin-right: 20px; margin-bottom: -10px;">
                    No apps asociated with this user
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>    
                {% endif %}
            </div>
        </div>
        <!-- <img style="position: absolute; top: 255px; left: 255px; z-index: 0;" src="{% static "images/Sogeti_Illustrations-64.png" %}" width="600" height="600"> -->

        <script src="{% static "jquery-3.3.1.slim.min.js" %}"></script>
        <script src="{% static "popper.min.js" %}"></script>
        <script src="{% static "bootstrap.min.js" %}"></script>  
        
        <!--<script src="{% static "file_input.js" %}"></script>-->
    </body>
</html>